### ISSUE TITLE
Unable to compile on Ubunutu 12.04 LTS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [castano/nvidia-texture-tools#185]
```
Ubuntu 12.04 LTS
GCC 4.6.3-1ubuntu5

What steps will reproduce the problem?
1. make

Scanning dependencies of target nvthread
[ 34%] Building CXX object src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o
/home/vagrant/nvidia-texture-tools-read-only/src/nvthread/nvthread.cpp: In 
function `unsigned int nv::hardwareThreadCount()': 
/home/vagrant/nvidia-texture-tools-read-only/src/nvthread/nvthread.cpp:29:20: 
error: `_SC_NPROCESSORS_ONLN' was not declared in this scope 
/home/vagrant/nvidia-texture-tools-read-only/src/nvthread/nvthread.cpp:29:40: 
error: `sysconf' was not declared in this scope
make[2]: *** [src/nvthread/CMakeFiles/nvthread.dir/nvthread.cpp.o] Error 1

What is the expected output? What do you see instead?
No error

Please use labels and text to provide additional information.

```

Original issue reported on code.google.com by `jernk...@gmail.com` on 5 Feb 2013 at 3:31

Attachments:
- [fixthread.patch](https://storage.googleapis.com/google-code-attachments/nvidia-texture-tools/issue-185/comment-0/fixthread.patch)
