### ISSUE TITLE
Mac compile problem (easy fix)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [castano/nvidia-texture-tools#103]
```
What steps will reproduce the problem?
1.  Compile on OSX 10.6
1.1. configure
1.2. make -> fails here

What is the expected output? What do you see instead?
make gives this error: "In file included from 
./nvidia-texture-tools/src/nvcore/Debug.cpp:41:
/usr/include/ucontext.h:42:2: error: #error ucontext routines are deprecated, 
and require 
_XOPEN_SOURCE to be defined"

What version of the product are you using? On what operating system?
2.0.6 on OSX 10.6.1

Please provide any additional information below.
Apple deprecated the functions to manipulate ucontexts, but not the structure 
for them. 
Including just the file with the struct fixes the problem. This solution was 
discovered by Joe of 
Duraian Software ( 
http://duriansoftware.com/joe/PSA:-avoiding-the-%22ucontext-routines-
are-deprecated%22-error-on-Mac-OS-X-Snow-Leopard.html )
```

Original issue reported on code.google.com by `gabebear@gmail.com` on 12 Oct 2009 at 5:49
