### ISSUE TITLE
GCC 5.4 chokes on "static enum" in etcpack.cxx

### ISSUE THREAD

**Issue by floooh** [castano/nvidia-texture-tools#254]
I'm trying to compile on Linux with GCC 5.4, and get compile errors in extern/etcpack/etcpack.cxx:

```
/home/ubuntu/nvidia-texture-tools/extern/etcpack/etcpack.cxx:163:17: error: a storage class can only be specified for objects and functions
    PATTERN_T = 1};
```
The problem are the 'static enum' in there, removing the static makes it work.

**Comment by castano** [comment]
Thanks for pointing that out. I've disabled etcpack. I've only been using it for reference and don't plan to actually rely on it.
