### ISSUE TITLE
Can't compile with PNG 1.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [castano/nvidia-texture-tools#169]
```
What steps will reproduce the problem?
1.Try to link Texture tools against libpng 1.5


What is the expected output? What do you see instead?
/Users/pschuchardt/Downloads/nvidia-texture-tools-read-only/src/nvimage/ImageIO.
cpp: In function ‘void user_read_data(png_struct*, png_byte*, png_size_t)’:
/Users/pschuchardt/Downloads/nvidia-texture-tools-read-only/src/nvimage/ImageIO.
cpp:606: error: invalid use of incomplete type ‘struct png_struct_def’
/usr/local/include/png.h:825: error: forward declaration of ‘struct 
png_struct_def’

See libPNG for details:
http://www.libpng.org/pub/png/libpng.html

What version of the product are you using? On what operating system?
Mac OS X 10.6
NVTT 2.0 svn

Please provide any additional information below.

```

Original issue reported on code.google.com by `vpica...@gmail.com` on 12 Dec 2011 at 9:17

**Comment by castano** [comment]
Closing as duplicate. See issue 193 for a fix.
